### PR TITLE
timer class & source class

### PR DESCRIPTION
**Pull request by 0xedl**

### CODE REVIEW

**Comment by marc-gav** [comment]
Looks good to me

**Comment by Duzzuti** [comment]
i will write an unittest for that class and do some small adjustments to match the codebase (e.g. unsigned long -> u_int64_t)

**Comment by Duzzuti** [comment]
resolves #8

**Review by Duzzuti — APPROVED** [review]
great class and it works correctly.
I just added the unittest and fixed this bug in the source file
```diff
-timer::
+Timer::
```
i have also changed a few types so that the codebase remains consistent.

Thanks for contributing

**Pull request merged**
