### PR TITLE
updated password validation function

### LINKED ISSUE #1: [NTH] User inputs invalid password
- **Difficulty (1-10):**
1
- **Location/Files:**
look in pwfunc/isPasswordValid() and app/askForPasswd()
- **Current behaviour:**
If the user inputs an invalid password, the current response is just a message that the password was illegal.
- **Wished behaviour:**
You have to implement a function that returns why the password was not valid.

### PR DESCRIPTION
**Pull request by Tonystark121**
Fixes #1 
updated passwd validation function.

### CODE REVIEW

**Comment by Duzzuti** [comment]
read this first
#1 https://github.com/Duzzuti/passwd-manager/issues/1#issuecomment-1552741089

**Comment by Tonystark121** [comment]
resolves #1

**Review by Duzzuti — COMMENTED** [review]
now we have finally fixed this

**Comment by Tonystark121** [comment]
Can you give me some feedback on changes that I have made through PR, it would help me in future endeavours🙂🙂

**Comment by Duzzuti** [comment]
Of course:
1. in c++, there is usally for every <name>.cpp file an header file <name>.h (usually in an include folder) that contains declarations. That means that you have to change the declarations there as well. Just learn about header files (search in the internet)
2. you should not declare a second class in a cpp file. Every class should be in its own file (like in java)
3.  also that class getError was unecessary. Look up some basic OOP concepts (that will help you in many languages). You should only declare a class if you wanna bundle some functionalitiy or attributes
4. in your first commit you created a function that takes the PASS_CHAR_SET as an input. But in this case PASS_CHAR_SET is a global variable. You can access from everywhere in your program. (that parameter was not necessary)
5. in cpp the string type is named std::string

That is all that i think about right now. I think OOP concepts are really important. You can go through the last commit of this PR https://github.com/Duzzuti/passwd-manager/pull/9/commits/f8245eb9fb8e2ef4c51c62f47a54f29bd6ca146b and try to understand what i did there. Ask if you need further explanation.

Thanks for contributing :)

**Pull request merged**
